-- Seed Music Trivia Questions
-- These are initial questions to get the game started

INSERT INTO trivia_questions (category, difficulty, question, correct_answer, incorrect_answers) VALUES
-- Easy Questions
('music', 'easy', 'Which band performed the song "Bohemian Rhapsody"?', 'Queen', ARRAY['The Beatles', 'Led Zeppelin', 'Pink Floyd']),
('music', 'easy', 'Who is known as the "King of Pop"?', 'Michael Jackson', ARRAY['Elvis Presley', 'Prince', 'James Brown']),
('music', 'easy', 'Which instrument does Jimi Hendrix famously play?', 'Electric Guitar', ARRAY['Piano', 'Drums', 'Bass Guitar']),
('music', 'easy', 'Who sang "I Will Always Love You" in The Bodyguard?', 'Whitney Houston', ARRAY['Mariah Carey', 'Celine Dion', 'Aretha Franklin']),
('music', 'easy', 'Which artist released the album "Purple Rain"?', 'Prince', ARRAY['Michael Jackson', 'David Bowie', 'George Michael']),
('music', 'easy', 'What band was Freddie Mercury the lead singer of?', 'Queen', ARRAY['The Rolling Stones', 'AC/DC', 'Aerosmith']),
('music', 'easy', 'Who wrote "Imagine"?', 'John Lennon', ARRAY['Paul McCartney', 'George Harrison', 'Bob Dylan']),
('music', 'easy', 'Which artist is known for the song "Thriller"?', 'Michael Jackson', ARRAY['Prince', 'Madonna', 'Whitney Houston']),
('music', 'easy', 'What instrument is Ringo Starr known for playing?', 'Drums', ARRAY['Guitar', 'Bass', 'Keyboards']),
('music', 'easy', 'Who sang "Like a Virgin"?', 'Madonna', ARRAY['Cyndi Lauper', 'Whitney Houston', 'Janet Jackson']),
('music', 'easy', 'What was the name of Michael Jackson''s pet chimpanzee?', 'Bubbles', ARRAY['Fluffy', 'Max', 'Buddy']),
('music', 'easy', 'Which Beatles song starts with "Close your eyes and I''ll kiss you"?', 'Tomorrow Never Knows', ARRAY['Strawberry Fields Forever', 'I Am the Walrus', 'Lucy in the Sky with Diamonds']),
('music', 'easy', 'What year was Bob Marley born?', '1945', ARRAY['1940', '1950', '1948']),
('music', 'easy', 'Who is known as the "Queen of Soul"?', 'Aretha Franklin', ARRAY['Diana Ross', 'Gladys Knight', 'Chaka Khan']),
('music', 'easy', 'Which band released the album "Abbey Road"?', 'The Beatles', ARRAY['The Rolling Stones', 'Led Zeppelin', 'The Who']),
('music', 'easy', 'What instrument does Louis Armstrong famously play?', 'Trumpet', ARRAY['Saxophone', 'Piano', 'Trombone']),
('music', 'easy', 'Who sang "Rolling in the Deep"?', 'Adele', ARRAY['Amy Winehouse', 'Norah Jones', 'Sara Bareilles']),
('music', 'easy', 'What was Elvis Presley''s middle name?', 'Aaron', ARRAY['Allen', 'Albert', 'Andrew']),
('music', 'easy', 'Which artist released the album "1989"?', 'Taylor Swift', ARRAY['Katy Perry', 'Ariana Grande', 'Selena Gomez']),
('music', 'easy', 'What genre is associated with Bob Marley?', 'Reggae', ARRAY['Blues', 'Jazz', 'Country']),
('music', 'easy', 'Who wrote "Hallelujah" which was popularized by Leonard Cohen?', 'Leonard Cohen', ARRAY['Bob Dylan', 'Paul Simon', 'Neil Young']),
('music', 'easy', 'What was the first music video played on MTV?', 'Video Killed the Radio Star', ARRAY['Take On Me', 'Billie Jean', 'Girls Just Want to Have Fun']),
('music', 'easy', 'Which band was Mick Jagger a member of?', 'The Rolling Stones', ARRAY['The Beatles', 'The Who', 'Cream']),
('music', 'easy', 'Who sang "Wannabe" by the Spice Girls?', 'The Spice Girls', ARRAY['Destiny''s Child', 'TLC', 'En Vogue']),

-- Medium Questions
('music', 'medium', 'What year was Michael Jackson''s "Thriller" released?', '1982', ARRAY['1980', '1984', '1979']),
('music', 'medium', 'What was Elvis Presley''s first number-one hit?', 'Heartbreak Hotel', ARRAY['Hound Dog', 'Jailhouse Rock', 'Love Me Tender']),
('music', 'medium', 'What year did The Beatles break up?', '1970', ARRAY['1968', '1972', '1969']),
('music', 'medium', 'What is the best-selling album of all time?', 'Thriller', ARRAY['Back in Black', 'The Dark Side of the Moon', 'Bat Out of Hell']),
('music', 'medium', 'Which band released "Stairway to Heaven"?', 'Led Zeppelin', ARRAY['Pink Floyd', 'The Who', 'Deep Purple']),
('music', 'medium', 'Who was the lead singer of Nirvana?', 'Kurt Cobain', ARRAY['Eddie Vedder', 'Chris Cornell', 'Layne Staley']),
('music', 'medium', 'What year did Elvis Presley die?', '1977', ARRAY['1975', '1979', '1980']),
('music', 'medium', 'Which artist recorded "Hotel California"?', 'Eagles', ARRAY['Fleetwood Mac', 'The Doobie Brothers', 'Steely Dan']),
('music', 'medium', 'What was the name of The Beatles'' first album?', 'Please Please Me', ARRAY['With The Beatles', 'A Hard Day''s Night', 'Help!']),
('music', 'medium', 'Who wrote "Respect" originally performed by Aretha Franklin?', 'Otis Redding', ARRAY['Aretha Franklin', 'James Brown', 'Sam Cooke']),
('music', 'medium', 'What band did Phil Collins drum for before going solo?', 'Genesis', ARRAY['Yes', 'Pink Floyd', 'The Police']),
('music', 'medium', 'Which artist released "Born to Run" in 1975?', 'Bruce Springsteen', ARRAY['Bob Seger', 'Tom Petty', 'John Mellencamp']),
('music', 'medium', 'What year was MTV launched?', '1981', ARRAY['1979', '1983', '1985']),
('music', 'medium', 'Who sang the original version of "Nothing Compares 2 U"?', 'The Family', ARRAY['Sinead O''Connor', 'Prince', 'Chris Isaak']),
('music', 'medium', 'What was Jimi Hendrix''s only US Top 40 hit?', 'All Along the Watchtower', ARRAY['Purple Haze', 'Hey Joe', 'Foxy Lady']),
('music', 'medium', 'What year did David Bowie release "Space Oddity"?', '1969', ARRAY['1967', '1971', '1972']),
('music', 'medium', 'Which band released "Hotel California" in 1976?', 'Eagles', ARRAY['Fleetwood Mac', 'America', 'Jackson Browne']),
('music', 'medium', 'What was the name of Bruce Springsteen''s backing band?', 'The E Street Band', ARRAY['The Heartbreakers', 'The Silver Bullet Band', 'The Max Weinberg Seven']),
('music', 'medium', 'Who produced Michael Jackson''s "Thriller" album?', 'Quincy Jones', ARRAY['George Martin', 'Phil Collins', 'Teddy Riley']),
('music', 'medium', 'What year was U2 formed?', '1976', ARRAY['1974', '1978', '1980']),
('music', 'medium', 'Which artist had a hit with "Bennie and the Jets"?', 'Elton John', ARRAY['Billy Joel', 'Stevie Wonder', 'James Taylor']),
('music', 'medium', 'What was the original name of the band Chicago?', 'Chicago Transit Authority', ARRAY['Windy City', 'Illinois', 'The Big Sound']),
('music', 'medium', 'Who sang "Every Breath You Take"?', 'The Police', ARRAY['Sting', 'Dire Straits', 'Phil Collins']),
('music', 'medium', 'What year did Madonna release her debut album?', '1983', ARRAY['1981', '1985', '1984']),
('music', 'medium', 'Which band released "Bohemian Rhapsody"?', 'Queen', ARRAY['Led Zeppelin', 'Pink Floyd', 'Genesis']),
('music', 'medium', 'What was the first #1 hit for The Beatles in America?', 'I Want to Hold Your Hand', ARRAY['She Loves You', 'Twist and Shout', 'Please Please Me']),
('music', 'medium', 'Who wrote "Imagine"?', 'John Lennon', ARRAY['Paul McCartney', 'George Harrison', 'Ringo Starr']),
('music', 'medium', 'What instrument does Sting play?', 'Bass Guitar', ARRAY['Guitar', 'Piano', 'Drums']),
('music', 'medium', 'Which artist released "Born in the U.S.A." in 1984?', 'Bruce Springsteen', ARRAY['John Fogerty', 'Tom Petty', 'Bob Seger']),

-- Hard Questions
('music', 'hard', 'What was the original name of The Black Eyed Peas?', 'Atban Klann', ARRAY['Black Eyed Pods', 'The Peas', 'Urban Tribe']),
('music', 'hard', 'Which classical composer became deaf later in life?', 'Ludwig van Beethoven', ARRAY['Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert']),
('music', 'hard', 'What was the first music video played on MTV?', 'Video Killed the Radio Star', ARRAY['You Better Run', 'Thriller', 'Billie Jean']),
('music', 'hard', 'Which guitarist is known for playing a guitar made from a fireplace?', 'Brian May', ARRAY['Eddie Van Halen', 'Jimmy Page', 'Eric Clapton']),
('music', 'hard', 'What is Bono''s real name?', 'Paul David Hewson', ARRAY['David Evans', 'Adam Clayton', 'Larry Mullen']),
('music', 'hard', 'Which band had members nicknamed "Slash" and "Axl"?', 'Guns N'' Roses', ARRAY['Motley Crue', 'Poison', 'Def Leppard']),
('music', 'hard', 'What instrument does Yo-Yo Ma play?', 'Cello', ARRAY['Violin', 'Viola', 'Double Bass']),
('music', 'hard', 'Which rock band was originally called "The Pendletones"?', 'The Beach Boys', ARRAY['The Byrds', 'The Mamas and the Papas', 'The Turtles']),
('music', 'hard', 'What was Prince''s real name?', 'Prince Rogers Nelson', ARRAY['Prince William Nelson', 'Roger Prince Nelson', 'Prince Albert Nelson']),
('music', 'hard', 'Which singer was born Stefani Joanne Angelina Germanotta?', 'Lady Gaga', ARRAY['Katy Perry', 'Kesha', 'Sia']),
('music', 'hard', 'What year was the first Woodstock festival?', '1969', ARRAY['1967', '1970', '1968']),
('music', 'hard', 'Who played drums on most of The Beatles'' "White Album"?', 'Ringo Starr', ARRAY['Paul McCartney', 'John Lennon', 'A session drummer']),
('music', 'hard', 'What band was Dave Grohl in before Foo Fighters?', 'Nirvana', ARRAY['Soundgarden', 'Pearl Jam', 'Alice in Chains']),
('music', 'hard', 'Which Queen song was used in the film "Wayne''s World"?', 'Bohemian Rhapsody', ARRAY['We Will Rock You', 'We Are the Champions', 'Another One Bites the Dust']),
('music', 'hard', 'What was the first rap song to reach #1 on the Billboard Hot 100?', 'Rapture by Blondie', ARRAY['Rapper''s Delight', 'The Message', 'Walk This Way']),
('music', 'hard', 'Which album by Pink Floyd stayed on the Billboard 200 for 937 weeks?', 'The Dark Side of the Moon', ARRAY['The Wall', 'Wish You Were Here', 'Animals']),
('music', 'hard', 'Who was the youngest Beatle?', 'George Harrison', ARRAY['Ringo Starr', 'Paul McCartney', 'John Lennon']),
('music', 'hard', 'What color were Elvis Presley''s iconic blue suede shoes?', 'Blue', ARRAY['White', 'Black', 'He never owned blue suede shoes']),
('music', 'hard', 'Which artist has won the most Grammy Awards?', 'Beyoncé', ARRAY['Georg Solti', 'Quincy Jones', 'Alison Krauss']),
('music', 'hard', 'What is the longest-running song on the Billboard Hot 100?', 'Blinding Lights', ARRAY['Shape of You', 'Uptown Funk', 'Old Town Road']),
('music', 'hard', 'What was the name of John Lennon''s first wife?', 'Cynthia Powell', ARRAY['Yoko Ono', 'Linda McCartney', 'Pattie Boyd']),
('music', 'hard', 'Which artist holds the record for most consecutive #1 hits on the Billboard Hot 100?', 'Whitney Houston', ARRAY['Mariah Carey', 'Michael Jackson', 'Madonna']),
('music', 'hard', 'What was the original title of Bob Dylan''s "Blowin'' in the Wind"?', 'How Many Roads', ARRAY['Answer Me', 'Forever Young', 'The Times They Are A-Changin''']),
('music', 'hard', 'Which band released "The Joshua Tree" in 1987?', 'U2', ARRAY['R.E.M.', 'The Cure', 'Echo & the Bunnymen']),
('music', 'hard', 'What instrument did Stevie Ray Vaughan primarily play?', 'Electric Guitar', ARRAY['Bass Guitar', 'Piano', 'Saxophone']),
('music', 'hard', 'Who was the first female artist to have four #1 hits from one album?', 'Whitney Houston', ARRAY['Mariah Carey', 'Celine Dion', 'Shania Twain']),
('music', 'hard', 'What was the name of Elvis Presley''s twin brother who was stillborn?', 'Jesse Garon Presley', ARRAY['James Aaron Presley', 'John Allen Presley', 'Robert Aaron Presley']),
('music', 'hard', 'Which classical piece was composed by Beethoven as a birthday gift for Josephine Brunsvik?', 'Für Elise', ARRAY['Moonlight Sonata', 'Ode to Joy', 'Pathetique Sonata']),
('music', 'hard', 'What was the first commercially released MP3?', 'Tom''s Diner by Suzanne Vega', ARRAY['Smells Like Teen Spirit', 'Losing My Religion', 'One']),
('music', 'hard', 'Which artist has the most Billboard Music Awards of all time?', 'Taylor Swift', ARRAY['Michael Jackson', 'Adele', 'Bruno Mars']),
('music', 'hard', 'What was the original name of the band that became The Doors?', 'The Psychedelic Rangers', ARRAY['The Wild Ones', 'The Crystal Ship', 'Break on Through']),
('music', 'hard', 'Who has won the most Grammys out of these four artists?', 'Weird Al Yankovic', ARRAY['Freddie Mercury', 'Diana Ross', 'Jimi Hendrix']),
('music', 'easy', 'Steven Van Zandt, who played Silvio Dante in The Sopranos, was originally known for his guitar work with…', 'Bruce Springsteen', ARRAY['Warren Zevon', 'Cat Stevens', 'Tom Petty']),

-- New batch of questions
('music', 'medium', 'What was Johnny Cash''s name at birth?', 'J.R. Cash', ARRAY['John Cash', 'Jack Cash', 'Johnathon Cash']),
('music', 'medium', 'What was Jerry Garcia''s birth name?', 'Jerome Garcia', ARRAY['Gerald Garcia', 'Jerry Garcia', 'Jerry Mackerman']),
('music', 'hard', 'Kid Congo Powers was known for being a member of what bands?', 'All of the above', ARRAY['The Gun Club', 'The Cramps', 'Nick Cave and the Bad Seeds']),
('music', 'hard', 'In 1947, Ahmet Ertegun and Herb Abramson co-founded which record label?', 'Atlantic Records', ARRAY['Motown', 'Sun Records', 'Stax Records']),
('music', 'easy', 'Aretha Franklin was the queen of what genre?', 'Soul', ARRAY['Rock and Roll', 'The Blues', 'Jazz']),
('music', 'medium', 'What artist was known as "Brother Ray"?', 'Ray Charles', ARRAY['Stevie Ray Vaughan', 'Ray LaMontagne', 'Billy Ray Cyrus']),
('music', 'hard', 'What year was Wilson Pickett inducted into the Rock and Roll Hall of Fame?', '1991', ARRAY['1983', '1998', '2005']),
('music', 'hard', 'Who was known as "The Sultans of Sweat"?', 'Sam and Dave', ARRAY['Ike and Tina Turner', 'Captain and Tennille', 'Simon and Garfunkel']),
('music', 'medium', 'Who wrote "(Sittin'' On) The Dock of the Bay"?', 'Steve Cropper and Otis Redding', ARRAY['Captain and Tennille', 'Steve Cropper and Sam Cooke', 'Otis Redding and Donald "Duck" Dunn']),
('music', 'hard', 'Who is most widely recognized for coining the term "rock and roll"?', 'Alan Freed', ARRAY['Chuck Berry', 'Sam Phillips', 'Ahmet Ertegun']),
('music', 'medium', 'What rock and roll pioneer is best known for his recording of "Rock Around the Clock"?', 'Bill Haley', ARRAY['Chuck Berry', 'Little Richard', 'Jerry Lee Lewis']),
('music', 'medium', 'David Robert Jones gained fame with what stage name?', 'David Bowie', ARRAY['Davy Jones', 'Robert Johnson', 'Eazy-E']),
('music', 'medium', 'The Who had a long list of hit songs in the 60s and 70s, mostly written by whom?', 'Pete Townshend', ARRAY['Roger Daltrey', 'Bernie Taupin', 'Harry Nilsson']),
('music', 'medium', '"Maybellene" and "Rock and Roll Music" were big hits in the 50s for which artist?', 'Chuck Berry', ARRAY['Little Richard', 'Muddy Waters', 'Jerry Lee Lewis']),
('music', 'medium', 'Which artist had a huge hit album with The Stranger (1977)?', 'Billy Joel', ARRAY['Elton John', 'Randy Newman', 'Jim Croce']),
('music', 'hard', 'Yoko Ono was born in what year?', '1933', ARRAY['1920', '1942', '1943']),
('music', 'medium', 'Richard Wayne Penniman was best known as whom?', 'Little Richard', ARRAY['Richard Thompson', 'Slick Rick', 'Richard Marx']),
('music', 'hard', 'Who was the bass player for The Band?', 'Rick Danko', ARRAY['Robbie Robertson', 'Levon Helm', 'Leland Sklar']),
('music', 'medium', 'What was Bob Dylan''s birth name?', 'Robert Zimmerman', ARRAY['Dylan Zimmerman', 'Robert Ritchie', 'Robert Dylan']),
('music', 'hard', 'The Talking Heads hit "Take Me to the River" was originally written by whom?', 'Al Green', ARRAY['Shel Silverstein', 'Bob Dylan', 'Harry Chapin']),
('music', 'hard', 'Country singer Mickey Gilley and televangelist Jimmy Swaggart were both cousins with which rock and roll legend?', 'Jerry Lee Lewis', ARRAY['Elvis Presley', 'Buddy Holly', 'Jimi Hendrix']);

